// <auto-generated>

using UnityEngine;
using UnityEngine.UI;
using ible.Foundation.UI;

namespace ible.GameModule.UI.HeroUI
{
    public abstract class HeroUITemplate : BaseUIView
    {
        [SerializeField]
        protected Button hideHero;
        [SerializeField]
        protected Button showClan;
        [SerializeField]
        protected Text textTMP;
        
        protected sealed override void Awake()
        {   
            base.Awake();
            hideHero.onClick.AddListener(OnClickHideHero);
            showClan.onClick.AddListener(OnClickShowClan);
        }
        
        protected abstract void OnClickHideHero();
        protected abstract void OnClickShowClan();
    }
}
