// <auto-generated>

using UnityEngine;
using UnityEngine.UI;
using ible.Foundation.UI;

namespace ible.GameModule.UI.ClanUI
{
    public abstract class ClanUITemplate : BaseUIView
    {
        [SerializeField]
        protected Button hideAll;
        [SerializeField]
        protected Button hideClan;
        
        protected sealed override void Awake()
        {   
            base.Awake();
            hideAll.onClick.AddListener(OnClickHideAll);
            hideClan.onClick.AddListener(OnClickHideClan);
        }
        
        protected abstract void OnClickHideAll();
        protected abstract void OnClickHideClan();
    }
}
