// <auto-generated>

using UnityEngine;
using ible.Foundation.UI;
using ible.Foundation;
using UnityEngine.UI;

namespace ible.GameModule.UI.TickerUI
{
    public abstract class TickerUITemplate : BaseUIView
    {
        [SerializeField]
        protected Text textTMP;
        
        protected override void Awake()
        {   
            base.Awake();
        }
        
    }
}
